providers:
  gsm:
    kind: google_secretmanager
    maps:
    - id: shared
      path: projects/xxxxxxxx
      keys:
        DUNEBOT_GITHUB_APP_INTEGRATION_ID: DUNEBOT_GITHUB_APP_INTEGRATION_ID
        DUNEBOT_GITHUB_APP_PRIVATE_KEY: DUNEBOT_GITHUB_APP_PRIVATE_KEY
        DUNEBOT_GITHUB_APP_WEBHOOK_SECRET: DUNEBOT_GITHUB_APP_WEBHOOK_SECRET
        DUNEBOT_GITHUB_OAUTH_CLIENT_ID: DUNEBOT_GITHUB_OAUTH_CLIENT_ID
        DUNEBOT_GITHUB_OAUTH_CLIENT_SECRET: DUNEBOT_GITHUB_OAUTH_CLIENT_SECRET
        DUNEBOT_JWT_PRIVATE_KEY: DUNEBOT_JWT_PRIVATE_KEY
        DUNEBOT_JWT_PUBLIC_KEY: DUNEBOT_JWT_PUBLIC_KEY
        DUNEBOT_GITHUB_TOKEN: DUNEBOT_GITHUB_TOKEN

  dotenv:
    kind: dotenv
    maps:
      - id: local
        path: .env
